encoding: utf-8

baseurl : http://js-ku.com
permalink : /:categories/:title.html
markdown: kramdown
# paginate: 5
# paginate_path: "page:num"
# paginate_path: "page:num"

##首页头部信息
indet_title: js开发库 - 开放，分享与协作 
index_keyword: 开源网站,共同开发,javaScritp 教程,java 教程,ruby 教程,python 教程,html5 教程,css3 教程,web app 教程,cocos-j s教程
index_description: js开发库，协作开发，
index_author: https://github.com/Da-Li/js-ku

